# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- name: Create cassandra service files
  become: true
  template:
    src: cassandra.service.j2
    dest: /etc/systemd/system/cassandra.service
    mode: 0644
- name: restart systemctl daemon
  become: true
  command: systemctl daemon-reload
- name: Enable cassandra services on boot
  become: true
  command: systemctl enable cassandra.service
