# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
- include_tasks: update-linux-settings.yml
- include_tasks: add-cassandra-user.yml
- include_tasks: install-apache-cassandra.yml
- include_role: name=configure-cassandra-nodes
- include_tasks: create-cassandra-services.yml
- include_tasks: start-cassandra-services.yml
