# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- name: Get volume device
  shell: "lsblk -d --output NAME | sed -n 2p"
  register: device
- name: Update SDA queue settings
  become: true
  shell: chdir="/sys/block/{{ device.stdout }}/queue/" {{ item }}
  with_items:
    - echo 1 > ./nomerges
    - echo 8 > ./read_ahead_kb
    - echo deadline > ./scheduler
- name: Change clocksource to Time Stamp Counter
  become: true
  shell: echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource
- name: Copy SYSCTL config
  become: true
  copy:
    src: 90-sysctl-increase-max-values.conf
    dest: /etc/sysctl.d/90-sysctl-increase-max-values.conf
    mode: 0644
- name: Apply SYSCTL config settings
  become: true
  command: sysctl -p /etc/sysctl.d/90-sysctl-increase-max-values.conf
- name: Copy PAM Limits config
  become: true
  copy:
    src: 90-limits-all-users-unlimited.conf
    dest: /etc/security/limits.d/90-limits-all-users-unlimited.conf
    mode: 0644
- name: Ensure swap mount is {{ cassandra_swap_mode }}
  become: true
  command: swap{{ cassandra_swap_mode }} -a
  